---
excludes:
  paths:
  - pattern: "Plugin-FS/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Plugin-JMS/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Weblogic/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Wildfly/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Core/Domibus-MSH-swagger/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Core/Domibus-MSH-distribution/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."    

  - pattern: "Domibus-DSS/domibus-dss-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-selenium-ui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-soapui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Plugin-WS/Domibus-default-ws-plugin-backend-ws-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: ".ort.yml"
    reason: "DOCUMENTATION_OF"
    comment: "This directory contains ort exclusions et al."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

resolutions:
  rule_violations:
    - message: ".*EUPL-1.2.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore will not be an issue."
    - message: ".*EUPL-1.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and EUPL-1.1 is upward compatible and therefore not an issue."
    - message: ".*GPL-2.0-only WITH Universal-FOSS-exception-1.0.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with Universal FOSS Exception 1.0 is acceptable. The exception allows for compatible linking with other FOSS projects."
    - message: ".*GPL-2.0-only WITH LicenseRef-scancode-mysql-linking-exception-2018.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with LicenseRef-scancode-mysql-linking-exception-2018. The exception allows for compatible linking with other FOSS projects."
    - message: "proprietary-free license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "proprietary-free license LicenseRef-IBM-US-Government-Restriction in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "property:non-commercial license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
