---
excludes:
  paths:
  - pattern: "Plugin-FS/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Plugin-JMS/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Weblogic/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Wildfly/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Core/Domibus-MSH-swagger/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."

  - pattern: "Core/Domibus-MSH-distribution/**"
    reason: "OPTIONAL_COMPONENT_OF"
    comment: "Not included in distributed build artifacts."    

  - pattern: "Domibus-DSS/domibus-dss-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-selenium-ui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-soapui-tests/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Core/Domibus-MSH-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: "Plugin-WS/Domibus-default-ws-plugin-backend-ws-test/**"
    reason: "TEST_OF"
    comment: "This directory contains tests."

  - pattern: ".ort.yml"
    reason: "DOCUMENTATION_OF"
    comment: "This directory contains ort exclusions et al."

  scopes:
  - pattern: "checkstyle"
    reason: "BUILD_DEPENDENCY_OF"
    comment: "Packages for code styling checks (testing) only."

  - pattern: "devDependencies"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "jacocoAgent"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "jacocoAnt"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for code coverage (testing) only."

  - pattern: "test.*"
    reason: "TEST_DEPENDENCY_OF"
    comment: "Packages for testing only."

  - pattern: "annotationProcessor"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileClasspath"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

  - pattern: "compileOnly"
    reason: "DEV_DEPENDENCY_OF"
    comment: "Packages for development only."

resolutions:
  rule_violations:
    - message: ".*EUPL-1.2.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and therefore will not be an issue."
    - message: ".*EUPL-1.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "EUPL-1.2 is the main license of the project and EUPL-1.1 is upward compatible and therefore not an issue."
    - message: ".*GPL-2.0-only WITH Universal-FOSS-exception-1.0.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with Universal FOSS Exception 1.0 is acceptable. The exception allows for compatible linking with other FOSS projects."
    - message: ".*GPL-2.0-only WITH LicenseRef-scancode-mysql-linking-exception-2018.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "GPL-2.0-only with LicenseRef-scancode-mysql-linking-exception-2018. The exception allows for compatible linking with other FOSS projects."
    - message: "proprietary-free license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "proprietary-free license LicenseRef-IBM-US-Government-Restriction in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "property:non-commercial license LicenseRef-scancode-sun-prop-non-commercial in Maven:javax:javaee-api:7.0."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "Later version of the exact same files are licensed under CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0. This information is from version 8.0.1. of the same package."
    - message: "copyleft-strong license GPL-2.0-or-later in Maven:org.hibernate.orm:hibernate-core:6.4.4.Final."
      reason: "CANT_FIX_EXCEPTION"
      comment: "The package does not include any GPL-2.0-or-later licensed code. The hit is false."
    - message: ".*LicenseRef-scancode-ecma-documentation.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "The LicenseRef-scancode-ecma-documentation license allows redistributing without modifications. As long as the files licensed with said license is redistributed without modifications, the violation is acceptable."
    - message: ".*LicenseRef-scancode-ms-specification.*"
      reason: "NOT_MODIFIED_EXCEPTION"
      comment: "The LicenseRef-scancode-ecma-documentation license allows redistributing without modifications. As long as the files licensed with said license is redistributed without modifications, the violation is acceptable."
    - message: ".*LicenseRef-scancode-jsr-107-jcache-spec.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: ".*LicenseRef-scancode-sun-jsr-spec-04-2006.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: ".*LicenseRef-scancode-sun-sdk-spec-1.1.*"
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "A specification license."
    - message: "commercial license LicenseRef-scancode-proprietary-license in Maven:javax.xml.bind:jaxb-api:2.3.1."
      reason: "LICENSE_ACQUIRED_EXCEPTION"
      comment: "This is a specification license from Bea Systems, Inc., a company later acquired by Oracle."

license_choices:
  repository_license_choices:
  - given: "CDDL-1.0 OR GPL-2.0-only"
    choice: "CDDL-1.0"
  - given: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND MIT AND SAX-PD AND EPL-1.0 AND (Apache-2.0 OR Apache-1.1 OR BSD-3-Clause OR LicenseRef-scancode-public-domain OR LicenseRef-scancode-indiana-extreme) AND (MIT OR GPL-1.0-or-later)"
    choice: "BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND MIT AND SAX-PD AND EPL-1.0 AND LicenseRef-scancode-public-domain AND MIT"
  - given: "(EPL-2.0 OR Apache-2.0) AND GPL-2.0-only WITH Classpath-exception-2.0"
    choice: "Apache-2.0 AND GPL-2.0-only WITH Classpath-exception-2.0"
  - given: "(EPL-2.0 OR Apache-2.0) AND EPL-2.0 AND Apache-2.0 AND CDDL-1.0 AND (CDDL-1.1 OR GPL-2.0-only WITH Classpath-exception-2.0) AND BSD-3-Clause"
    choice: "Apache-2.0 AND EPL-2.0 AND Apache-2.0 AND CDDL-1.0 AND CDDL-1.1 AND BSD-3-Clause"
  - given: "EPL-2.0 OR GPL-2.0-only WITH Classpath-exception-2.0"
    choice: "EPL-2.0"
  - given: "NPL-1.1 OR GPL-2.0-or-later"
    choice: "NPL-1.1"
  - given: "(MIT OR GPL-2.0-or-later) AND (MIT OR BSD-3-Clause AND GPL-2.0-or-later)"
    choice: "MIT AND MIT"
  - given: "(MIT OR GPL-2.0-only) AND BSD-3-Clause"
    choice: "MIT AND BSD-3-Clause"
  - given: "MIT OR GPL-2.0-only"
    choice: "MIT"
  - given: "(EPL-2.0 OR BSD-3-Clause OR GPL-2.0-only WITH Classpath-exception-2.0) AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND OFL-1.1 AND MIT AND (GPL-2.0-only OR GPL-2.0-only WITH Classpath-exception-2.0) AND EPL-2.0"
    choice: BSD-3-Clause AND Apache-2.0 AND W3C AND LicenseRef-scancode-public-domain AND OFL-1.1 AND MIT AND GPL-2.0-only WITH Classpath-exception-2.0 AND EPL-2.0