version: '3.2'
services:
  mysqlc2:
    image: domibustest/domibus-mysql:${DOMIBUS_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
  tomcatc2:
    image: domibustest/domibus-tomcat:${DOMIBUS_VERSION}
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=mysqlc2
      - DB_PORT=3306
      - DB_USER=edelivery
      - DB_PASS=edelivery
      - CHECK_DEFAULT_PASSWD=false
    ports:
      - "9088:8080"
    command: dockerize -wait tcp://mysqlc2:3306 -timeout 20s
    depends_on:
      - mysqlc2
