version: '3.2'
services:
  ##
  ## Corner 2 - Domibus Tomcat MySQL Red Configuration
  ##
  mysqlc2:
    image: domibustest/domibus-mysql:4.1.1-SNAPSHOT
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
  tomcatc2:
    image: domibustest/domibus-tomcat:4.1.1-SNAPSHOT
    environment:
      - DB_TYPE=MySQL
      - DB_HOST=mysqlc2
      - DB_PORT=3306
      - DB_USER=edelivery
      - DB_PASS=edelivery
      - CHECK_DEFAULT_PASSWD=false
    ports:
      - "9088:8080"
    volumes:
      - ./c2/conf/domibus/policies:/data/tomcat/conf/domibus/policies
    command: dockerize -wait tcp://mysqlc2:3306 -timeout 20s
    depends_on:
      - mysqlc2
