#
# Docker compose project used to startup the test environment.

version: '3.5'
services:
  #
  # CORNER 2
  #

  # oracle  db
  # todo setup also oracle version and edition as parameter
  wls12clst-oradb:
    image: domibustest/domibus-oracle${ORA_VERSION:-11.2.0.2}-${ORA_EDITION:-xe}:${DOMIBUS_VERSION:-4.2-SNAPSHOT}
    shm_size: '1gb'
    environment:
      - ORACLE_PWD=oracle
      - DOMIBUS_PASSWORD=domibus
      - DOMAINS_COUNT=2
      - DOMAIN_INIT_USERS=false
      - DOMIBUS_GENERAL_USER=domibus_general
      - DOMIBUS_DOMAIN_USER_PREFIX=domibus_domain
    #    expose:
    #      - "1521"
    volumes:
      - shared-status-folder:/opt/oracle/status/
    container_name: ${DOMIBUS_CORNER:-c2}-wls12clst-oradb
    networks:
      test-network:

  # weblogic admin server
  # NOTE: wlst connect does not support underscores in server name
  wls-admin:
    # depend of the startup of the db
    depends_on:
      - wls12clst-oradb
    command: [bash, -c, "for i in `seq 150`; do timeout 1  bash -c 'echo \" $$(ls /opt/oracle/status/)\"'; if [ -f '/opt/oracle/status/oracle.started' ]  ; then break;fi; echo \"$$i. Wait for database!\"; sleep 10;  done; /u01/oracle/startAdminServer.sh"]
    environment:
      - WL_ADMIN_HOST=localhost
      - DOMIBUS_VERSION=${DOMIBUS_VERSION:-4.2-SNAPSHOT}
      # database parameters must match wls12clst-oradb:
      - DB_HOST=${DOMIBUS_CORNER:-c2}-wls12clst-oradb
      - DB_USER=domibus_general
      - DB_PASS=domibus
      - DB_PORT=1521
      - DB_NAME=${ORA_SERVICE:-xe}
      - DOMAINS_COUNT=2
      - DOMAIN_ALIASES=blue_gw,red_gw
      - DOMIBUS_GENERAL_USER=domibus_general
      - DOMIBUS_DOMAIN_USER_PREFIX=domibus_domain
      - WL_CLUSTER_MODE=true
      - DOMIBUS_INIT_PROPERTIES="domibus.msh.pull.cron=0/10 * * * * ?||domibus.passwordPolicy.checkDefaultPassword=false"
    image: domibustest/domibus-weblogic122:${DOMIBUS_VERSION:-4.2-SNAPSHOT}
    container_name: ${DOMIBUS_CORNER:-c2}-wls12clst-admin
    #ports:
    # - "7001:7001"
    restart: always
    volumes:
      - shared-config-folder:/data
      - shared-status-folder:/opt/oracle/status/
    networks:
      test-network:

  wls-node-01:
    # depend of the startup of the db
    depends_on:
      - wls-admin
    command: [bash, -c, "for i in `seq 150`; do timeout 1  bash -c 'echo \" $$(ls /opt/oracle/status/)\"'; if [ -f '/opt/oracle/status/wls-admin.started' ]  ; then break;fi; echo \"$$i. Wait for admin server!\"; sleep 10;  done; /u01/oracle/startManagedServer.sh"]
    environment:
      - WL_ADMIN_HOST=${DOMIBUS_CORNER:-c2}-wls12clst-admin
      - MANAGED_SERV_NAME=managed-server-1
    image: domibustest/domibus-weblogic122:${DOMIBUS_VERSION:-4.2-SNAPSHOT}
    container_name: ${DOMIBUS_CORNER:-c2}-wls12clst-node-01
    #ports:
    #  - "8001:8001"
    restart: always
    volumes:
      - shared-config-folder:/data
      - shared-status-folder:/opt/oracle/status/
    networks:
      test-network:

  wls-node-02:
    # depend of the startup of the db
    depends_on:
      - wls-admin
    command: [bash, -c, "for i in `seq 150`; do timeout 1  bash -c 'echo \" $$(ls /opt/oracle/status/)\"'; if [ -f '/opt/oracle/status/wls-admin.started' ]  ; then break;fi; echo \"$$i. Wait for admin server!\"; sleep 10;  done; /u01/oracle/startManagedServer.sh"]
    environment:
      - WL_ADMIN_HOST=${DOMIBUS_CORNER:-c2}-wls12clst-admin
      - MANAGED_SERV_NAME=managed-server-2
    image: domibustest/domibus-weblogic122:${DOMIBUS_VERSION:-4.2-SNAPSHOT}
    container_name: ${DOMIBUS_CORNER:-c2}-wls12clst-node-02
    #ports:
    #  - "8002:8001"
    restart: always
    volumes:
      - shared-config-folder:/data
      - shared-status-folder:/opt/oracle/status/
    networks:
      test-network:

  httpd:
    depends_on:
      - wls-admin
    image: domibustest/edelivery-httpd:2.4.39
    environment:
      - VHOST_CORNER_HOSTNAME=edelivery.domibus.eu
      - NODES_COUNT=2
      - NODE_HOSTNAMES=${DOMIBUS_CORNER:-c2}-wls12clst-node-01,${DOMIBUS_CORNER:-c2}-wls12clst-node-02
      - NODE_PORT_NUMBERS=8001,8001
    hostname: ${DOMIBUS_CORNER:-c2}-wls12clst-httpd
    container_name: ${DOMIBUS_CORNER:-c2}-wls12clst-httpd
    ports:
      - "9008:80"
    restart: always
    networks:
      test-network:

volumes:
  shared-status-folder:
  shared-config-folder:

networks:
  test-network:
    driver: bridge
